mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('triangle/', include('triangle.urls')),
    path('admin/', admin.site.urls),
]

triangle/urls.py
from django.urls import path

from triangle.views import get_form, post_person, index, edit_person


app_name = 'triangle'
urlpatterns = [
    path('', index, name='index'),
    path('hypotenuse/', get_form, name='triangle_view'),
    path('person/', post_person, name='person_view'),
    path('person/<int:pk>/', edit_person, name='edit_person_view')
]

triangle/models.py
from django.db import models


class Person(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)

    def __str__(self):
        return self.first_name


class City(models.Model):
    city_name = models.CharField(max_length=100)

    def __str__(self):
        return str(self.city_name)


class Product(models.Model):
    product_name = models.CharField(max_length=250)

    def __str__(self):
        return str(self.product_name)


class Purveyor(models.Model):
    city_name = models.OneToOneField(
        City,
        on_delete=models.CASCADE,
        primary_key=True,
    )

    purveyor_name = models.CharField(max_length=100)

    def __str__(self):
        return str(self.purveyor_name)


class Client(models.Model):
    city_name = models.ForeignKey(
        City,
        on_delete=models.CASCADE
    )

    product_name = models.ManyToManyField(Product)

    client_name = models.CharField(max_length=100)
    client_email = models.EmailField(max_length=100)

    def __str__(self):
        return str(self.client_name)


class Logs(models.Model):
    path = models.CharField(max_length=200)
    method = models.CharField(max_length=50, choices=(('POST', 'POST'), ('GET', 'GET')))
    timestamp = models.DateField(auto_now_add=True)

    def __str__(self):
        return str(self.path)

triangle/forms.py
from django import forms

from triangle.models import Person


class TriangleForm(forms.Form):
    catet1 = forms.IntegerField(label='Катет №1', min_value=1, required=True)
    catet2 = forms.IntegerField(label='Катет №2', min_value=1, required=True)


class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = ['first_name', 'last_name', 'email']

catalog/views.py
# from django.shortcuts import render

# Create your views here.

triangle/views.py
from django.shortcuts import render, redirect, get_object_or_404

from triangle.forms import TriangleForm
from triangle.forms import PersonForm
from triangle.models import Person


def index(request):
    return render(request, 'triangle/index.html', {})


def get_form(request):
    hypotenuse = None
    if 'submit' in request.GET:
        form = TriangleForm(request.GET)
        if form.is_valid():
            catet1 = form.cleaned_data["catet1"]
            catet2 = form.cleaned_data["catet2"]
            hypotenuse = round(((catet1 ** 2 + catet2 ** 2) ** 0.5), 2)
    else:
        form = TriangleForm()
    return render(
        request, 'triangle/triangle_form.html',
        {
            'get_form': form,
            'hypotenuse': hypotenuse
        }
    )


def post_person(request):
    if request.method == 'POST':
        person_form = PersonForm(data=request.POST)
        if person_form.is_valid():
            Person.objects.create(
                first_name=person_form.cleaned_data['first_name'],
                last_name=person_form.cleaned_data['last_name'],
                email=person_form.cleaned_data['email']
            )
            return redirect("triangle:index")
    else:
        person_form = PersonForm()
    return render(
        request,
        "triangle/person_form.html",
        {
            'person_form': person_form,
        }
    )


def edit_person(request, pk):
    obj = get_object_or_404(Person, pk=pk)
    if request.method == 'POST':
        person_form = PersonForm(data=request.POST, instance=obj)
        if person_form.is_valid():
            person_form.save()
            return redirect("triangle:index")
    else:
        person_form = PersonForm(instance=obj)
    return render(
        request,
        "triangle/edit_person_form.html",
        {
            'person_form': person_form,
            'obj': obj,
        }
    )

templates/triangle/edit_person_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Editor</title>
</head>
<body>
<h1>Форма редактирования анкеты</h1>

<form action="{% url 'triangle:edit_person_view' pk=obj.pk %}" method="post">
    {% csrf_token %}
    {{ person_form.as_p }}
    <input type="submit" name="submit" value="OK">
    <input type="button" value="Назад" onClick='location.href="{% url 'triangle:index'  %}"'>
</form>

</body>
</html>

templates/triangle/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>
    <h1>Начальная страница</h1>
    <p><a href="{% url 'triangle:triangle_view' %}">Расчёт гипотенузы</a> </p>
    <p><a href="{% url 'triangle:person_view' %}">Форма создания анкеты</a> </p>
</body>
</html>

templates/triangle/person_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Person</title>
</head>
<body>
<h1>Форма создания анкеты</h1>

<form action="{% url 'triangle:person_view'  %}" method="post">
    {% csrf_token %}
    {{ person_form.as_p }}
    <input type="submit" name="submit" value="OK">
    <input type="button" value="Назад" onClick='location.href="{% url 'triangle:index'  %}"'>
</form>

</body>
</html>

templates/triangle/triangle_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Triangle</title>
</head>
<body>
<h1>Расчёт гипотенузы</h1>

{% if hypotenuse %}
    <h2>{{ hypotenuse }}</h2>
{% endif %}

<form action="{% url 'triangle:triangle_view'  %}" method="get">
    {{ get_form.as_p }}
    <input type="submit" name="submit" value="OK">
    <input type="button" value="Сброс" onClick='location.href="{% url 'triangle:triangle_view'  %}"'>
    <input type="button" value="Назад" onClick='location.href="{% url 'triangle:index'  %}"'>
</form>

</body>
</html>